import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideNavBar from './components/sideNavBar'
import Head from "next/head";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next demo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <Head>
        <title>Next demo</title>
    </Head>
      <body>
      <main className='bg-grey-100 min-h-screen'>
        <div className="layout">
          <SideNavBar/>
          {children}
        </div>
      </main>
      </body>
   </html>
  )
}